### ISSUE TITLE
Il est possible d'acceder au Heroku Frontend en HTTP (non securisé) - On ne devrait pas le permettre si possible

### ISSUE THREAD

**Issue by ghost** [gti525/h19-banque-1#107]

**Comment by francisprud** [comment]
Quand même complexe, ca doit être fait au niveau de l'application et non par heroku (sans commentaire) 

https://www.npmjs.com/search?q=express+ssl

**Comment by francisprud** [comment]
Francois a mentionné que tant qu'HTTPS fonctionne, c'est pas important que le HTTP fonctionne aussi ou non.
