### ISSUE TITLE
E05 - Liste de transactions

### ISSUE THREAD

**Issue by Jordanlamd** [gti525/h19-banque-1#15]
E05	En tant que client, je dois pouvoir accéder à la liste des transactions sur la carte de crédit et le compte courant.

**Comment by jeff348** [comment]
J'ai fait des modification dans le frontend, alors get mon dernier push

La classe avec la quelle tu vas travailler est  ShowTransaction

- Tu peux y accéder le lien "Liste des transaction"

Pour lister les transaction, il faudra que tu te sert du search pour ce faire, tu as un example de son utilisation dans homeclient. Il faut que quand je clique dans la liste des transaction de compte courant sa me montre juste les transaction du compte courant.

Pour ce faire tu peux essayer de trouver un moyen d'envoyer les information sur ce qui est cliquer dans "ShowTransaction" et ensuite faire le traitement. Je te laisse regarder sa.

De plus, les champs que le tableau devra avoir sera comme l'image. 

![Annotation 2019-03-15 013143.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c3937d3e2b5ff0012183e5a/125516c66e82c728ace21e0d46c99a942c9682bd86e6b103f60da1cd6416743e7851e37b21d6b27cec0037431f1d11f6140b1b56f6eb8c78a5bf3f70825d5fbcd76b5d27c63e17f8bc824dec55bd32975dc7e7e2de139db17770a599855d3f190f198cfa5f33a29e42c95bff48e45f18.png)
![Annotation 2019-03-15 013712.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c3937d3e2b5ff0012183e5a/125516c66e82c728ace21e0d46c99a942c9682bd86e6b103f60da1cd6416743e7851e37b21d6b479ed0037431f1d11f6140b1b56f6eb8c78a5bf3f70825d5fbcd76b5d27c63e17f8bc824dec55bd32975dc7e7e2de139db17770a599855d3f190f198cfa5f33a29149cc5cf44de85f18.png)
