### ISSUE TITLE
E07 - Remboursement de solde

### ISSUE THREAD

**Issue by Jordanlamd** [gti525/h19-banque-1#18]
En tant que client, je dois pouvoir rembourser le solde de ma carte de crédit partiellement ou en totalité à partir des fonds de mon compte courant.

**Comment by jeff348** [comment]
Je t'ai créer la page "CreditCardPayment" pour completer ton travail. Il est accesible à partir de la page homeclient.

Il faudra que tu envoie la request API suivant 

- Ajouter un champs pour le montant d'argent
- Il faudra que tu trouve un moyen d'envoyer à la vue "CreditCardPAyment" les informations du compte courant et son numero de carte de credit

Aide : Tu pourrais get les informations avec UsersU dans la vue CreditCardPayment et ensuite faire ton post. Plusieurs exemple dans le code

![Annotation 2019-03-15 013143.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c3937d3e2b5ff0012183e5a/125516c66e82c728ace21e0d46c99a942c9682bd86e6b103f60da1cd6416743e7851e37b21d6b27cec0037431f1d11f6140b1b56f6eb8c78a5bf3f70825d5fbcd76b5d27c63e17f8bc824dec55bd32975dc7e7e2de139db17770a599855d3c1e0f198cfa5f33a29148cf59ff43e55f18.png)
![Annotation 2019-03-15 014144.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c3937d3e2b5ff0012183e5a/125516c66e82c728ace21e0d46c99a942c9682bd86e6b103f60da1cd6416743e7851e37b21d1b27ceb0037431f1d11f6140b1b56f6eb8c78a5bf3f70825d5fbcd76b5d27c63e17f8bc824dec55bd32975dc7e7e2de139db17770a599855d3f160f198cfa5f33a2914ec95ff44ae35f18.png)
