### ISSUE TITLE
E08 - Transfert de fonds entre compte

### ISSUE THREAD

**Issue by Jordanlamd** [gti525/h19-banque-1#19]
En tant que client, je dois pouvoir transférer des fonds de mon compte courant vers le compte courant d'un autre client d'une banque.

**Comment by jeff348** [comment]
Je t'ai créer la vue TransferToOtherAccount"  pour effectuer ce travail.

- Ajouter deux champs : un pour le montant et l'autre pour le numéro bancaire de l'autre personne
- Aussi trouver un moyen pour envoyer l'information du compte courant à TransferToOtherAccount. 

Aide : Tu pourrais get les informations avec UsersU dans la vue TransferToOtherAccount et ensuite faire ton post. Plusieurs exemple dans le code


![Annotation 2019-03-15 013143.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c3937d3e2b5ff0012183e5a/125516c66e82c728ace21e0d46c99a942c9682bd86e6b103f60da1cd6416743e7851e37b21d6b27cec0037431f1d11f6140b1b56f6eb8c78a5bf3f70825d5fbcd76b5d27c63e17f8bc824dec55bd32975dc7e7e2de139db17770a599855d3f190f198cfa5f33a2914dc059fe42e55f18.png)
![Annotation 2019-03-15 014436.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c3937d3e2b5ff0012183e5a/125516c66e82c728ace21e0d46c99a942c9682bd86e6b103f60da1cd6416743e7851e37b21d1b77be90037431f1d11f6140b1b56f6eb8c78a5bf3f70825d5fbcd76b5d27c63e17f8bc824dec55bd32975dc7e7e2de139db17770a599855d3f190f198cfa5f33a2914dc05ef04ee85f18.png)

**Comment by Jordanlamd** [comment]
Note perso:
Bugs détectés:
- Refresh la page perd le data passé en paramètre de la page HomeClient. Bref, le solde du client ne s'affiche plus à moins qu'on retourne au homepage pour revenir dans Transfert.
-Accéder à la page Transfert via le NavBar, au lieu du bouton situé dans le homepage, ne passe pas en paramètres le data (solde et num. compte).
