### ISSUE TITLE
$$ Deplacer bouton PageAdmin/PageClient

### ISSUE THREAD

**Issue by ghost** [gti525/h19-banque-1#36]

**Comment by jeff348** [comment]
Essayer de le mettre dans la barre du haut. Peut-etre faire un nav-bar pour le mettre en haut 

https://bootswatch.com/flatly/

**Comment by francisprud** [comment]
Navbar ajoutée sur les deux pages login. Bug qui fait que le burger fonctionne pas; c'est pas dans le code du navbar, ca doit être ailleurs dans la page, surement un truc de container qui interfère. Je vais faire un autre case et revenir sur ce bug plus tard.

**Comment by francisprud** [comment]
Tâche terminée
