### ISSUE TITLE
$$ Dans rechercher clients, ajouter option searchAll

### ISSUE THREAD

**Issue by ghost** [gti525/h19-banque-1#37]

**Comment by jeff348** [comment]
Ajouter un bouton qui refait une recherche avec * pour qu'ils affiche tous le monde sauf les admin

**Comment by jeff348** [comment]
Bizarrement jeff348 est capable de se connecter dans la page client. Il ne devrait pas etre capable.

**Comment by jeff348** [comment]
GG c'est fait
