### ISSUE TITLE
Enlever le errorPage + le delete token dans la page ModifyPassword et mettre un alert avec un message significatif

### ISSUE THREAD

**Issue by jeff348** [gti525/h19-banque-1#91]

**Comment by Jordanlamd** [comment]
ModifyPassword a été renommé ResetPassword durant son implémentation vendredi passé. Et dans ce component, aucune errorPage et de delete token n'est présent; ils ont été retirer à la fin de l'implémentation. PAR CONTRE, la classe intermédiaire BeforeResetPassword (tu as peut-être confondu les deux classes) comporte ces 2 éléments. Ils vont être retirer de cette classe au lieu.
